version: 0.0
os: linux
files: 
  - source: ./code-pipeline-example
    destination: /home/appuser/code-pipeline-example
  - source: ./exec.sh
    destination: /home/appuser/code-pipeline-example
permissions:
  - object: /home/appuser/code-pipeline-example
    pattern: "**"
    owner: appuser
    group: appuser
    mode: 700
    type:
      - file
      - directory
